[workspace]
members = [
    "crates/vlmcsd-types",
    "crates/vlmcsd-crypto",
    "crates/vlmcsd-kmsdata",
    "crates/vlmcsd-protocol",
    "crates/vlmcsd-rpc",
    "crates/vlmcsd-network",
    "crates/vlmcsd-server",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
