#ifndef VLMCSD_H
#define VLMCSD_H

/* This file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Returns the library version as an integer.
 */
int vlmcsd_get_version(void);

/**
 * Returns a pointer to a null-terminated version string.
 */
const char *vlmcsd_get_emulator_version(void);

/**
 * Returns a pointer to the last error message.
 */
const char *vlmcsd_get_error_message(void);

/**
 * Starts the KMS server on the given port in a background thread.
 * Returns 0 on success, non-zero on error.
 */
uint32_t vlmcsd_start_server(int port);

/**
 * Stops the KMS server.
 * Returns 0 on success.
 */
uint32_t vlmcsd_stop_server(void);

/**
 * Processes a raw KMS request and returns a raw KMS response.
 *
 * `response_data` receives a pointer to the allocated response (caller must free with `vlmcsd_free`).
 * `response_len` receives the length of the response.
 *
 * Returns 0 on success.
 */
uint32_t vlmcsd_process_request(const uint8_t *request_data,
                                uintptr_t request_len,
                                uint8_t **response_data,
                                uintptr_t *response_len);

/**
 * Frees memory allocated by vlmcsd FFI functions.
 */
void vlmcsd_free(uint8_t *ptr, uintptr_t len);

/**
 * Returns the number of available SKU products in the embedded database.
 */
int vlmcsd_get_product_count(void);

/**
 * Gets the name of a product by index (0-based).
 * Caller must free the returned string with `vlmcsd_free_string`.
 */
char *vlmcsd_get_product_name(int index);

/**
 * Frees a string returned by vlmcsd FFI functions.
 */
void vlmcsd_free_string(char *ptr);

#endif  /* VLMCSD_H */
